//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class About {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal About() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication1.Resources.About", typeof(About).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each client or group has an English/spanish speaking Host that will meet you when you arrive and accompany you every step of the way. You are never alone, the host will be there to assist with the selection of a companion..
        /// </summary>
        public static string ParagraphFive {
            get {
                return ResourceManager.GetString("ParagraphFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accomodations are in  are in Casa&apos;s, not a hotel. Therefore you will not feel as though you are being judged by people you don&apos;t even know. We work with many different casa’s. You can find high end properties or a more standard house. Whatever your taste is, we are certain to that we can accommodate..
        /// </summary>
        public static string ParagraphFour {
            get {
                return ResourceManager.GetString("ParagraphFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our company was founded in 2013. However we chose to run with zero exposure at first, selected individuals along with the founders  were our guinea pigs. This gave us a chance to learn and grow the business before going live..
        /// </summary>
        public static string ParagraphOne {
            get {
                return ResourceManager.GetString("ParagraphOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have vacationed to all parts of the Caribbean.After traveling to places such as Mexico, Dominican Republic &amp; Jamaica..
        /// </summary>
        public static string ParagraphThree {
            get {
                return ResourceManager.GetString("ParagraphThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are a group of friends of over 15 years. We are composed up of married / divorced / single men aged 30 to 45.  We are not rich people so we know how to stretch a dollar when it needs to be done. We wanted to have a vacation for ourselves..
        /// </summary>
        public static string ParagraphTwo {
            get {
                return ResourceManager.GetString("ParagraphTwo", resourceCulture);
            }
        }
    }
}
